### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by RuachEl** [mrachinskiy/jewelcraft#12]
I'm having issues getting jewelcraft to work. I followed the instructions in the two previous issues. I've attached a screenshot of the problem
![screenshot](https://user-images.githubusercontent.com/47712630/52911995-ee76cd80-3270-11e9-9ee9-02ec2407281f.png)

**Comment by mrachinskiy** [comment]
JewelCraft v2.3 does not support Blender 2.7, you have to use JewelCraft v2.2.

**Comment by RuachEl** [comment]
I must say, your support is amazing. I did not expect an answer so quickly. And your fix worked. Thanks.
