### ISSUE TITLE
blender2.8version, when I select the kind of zem stone, it shows error message.

### ISSUE THREAD

**Issue by jesmina75** [mrachinskiy/jewelcraft#13]
like the title, I run into this error; 
![K-151](https://user-images.githubusercontent.com/49366787/55684024-7def5180-5981-11e9-85c1-590bebab3f80.png)

Thank you for your time in advance.

**Comment by mrachinskiy** [comment]
You are using outdated Blender 2.80 build, download the new one: https://builder.blender.org/download/

**Comment by jesmina75** [comment]
Thank you!
The problem is solved!
and thank you for the awesome addons, too.
 
-----Original Message-----
