### ISSUE TITLE
Enable Addon Issue Win 10 Laptop Jewelcraft 2.3.1

### ISSUE THREAD

**Issue by DavidJamie** [mrachinskiy/jewelcraft#15]
Removed existing Jewelcraft Addon
Restarted Blender 2.80
Edit / Preferences / Add on / Install / Jewelcraft 2.3.1 from zip
Appears to be installed
Click to enable Addon
ERROR - FILE NOT FOUND
C:\user\.....\Blender\\2.80\\Scripts\\addons\\jewelcraft-master\\assets\Icons

Note: I have installed the Addon successfully on my older desktop.

Any clues to what I have done wrong?

**Comment by mrachinskiy** [comment]
Please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.

**Comment by mrachinskiy** [comment]
You have downloaded add-on repository instead of release. Use link in the how to install guide to download release.

**Comment by DavidJamie** [comment]
Thank you for your prompt and accurate solution to my question. All is now OK.
