### ISSUE TITLE
Still Cannot Install on Blender 2.8.0 

### ISSUE THREAD

**Issue by kiri1121** [mrachinskiy/jewelcraft#18]
I downloaded Blender 2.8.0 to use the newer version of Jewelcraft, as you mentioned to do in my last post. I'm still having an issue downloading it. Now it says
![Untitled-1](https://user-images.githubusercontent.com/20896107/58125983-b9a74900-7bc6-11e9-9f1e-383b7823c52d.jpg)

**Comment by mrachinskiy** [comment]
It's says that you already tried to enable add-on. This error message is useless.

You should do the following:
1. Close Blender.
2. Open it.
3. Activate the add-on, screenshot the error message and send it here.

**Comment by kiri1121** [comment]
I apologize for my mistake. Here is a screenshot of the message:
![Untitled-1](https://user-images.githubusercontent.com/20896107/58140352-becebd00-7bf3-11e9-9583-a470c691a8d7.jpg)

**Comment by kiri1121** [comment]
I also tried to download the file from GitHub again and reinstall it. I received the same message.

**Comment by mrachinskiy** [comment]
You have downloaded add-on repository instead of release. Use link in the [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide to download release.

**Comment by GGlep1892** [comment]
Hi, i followed instructions but got the same error as above user. I followed your link and got jewelcraft-2_3_2 for the latest build of Blender 2.8.

![JC empty tool kit](https://user-images.githubusercontent.com/51529280/59157734-d5cf3500-8a64-11e9-94d0-09b4f5063d11.jpg)
![JC error message](https://user-images.githubusercontent.com/51529280/59157735-da93e900-8a64-11e9-9243-f4f0900c10f1.jpg)

**Comment by GGlep1892** [comment]
As you can see it partially installed but is not functional

**Comment by mrachinskiy** [comment]
@GGlep1892 try restarting Blender and see if error reappears.
