### ISSUE TITLE
Notice for Measurement / Product Report

### ISSUE THREAD

**Issue by bendicott67** [mrachinskiy/jewelcraft#19]
Where could I find a notice for the Measurement / Product Report ?

I'd like to give the shank size  to my founder with the Gem Map - It was possible with the previous versions, but I didn't find it in 2.3.2

Is the conversion ring size in the product report ? I didnt find it.

**Comment by mrachinskiy** [comment]
> Where could I find a notice for the Measurement / Product Report ?

What do you mean by "notice"?

> shank size

Add "Dimensions" measurement type for your shank object.

> Is the conversion ring size in the product report ?

JewelCraft v2.3.2 does not have ring size implementation. It's planned for v2.3.3.

**Comment by bendicott67** [comment]
Sorry 'notice' is a bad french translation. I mean 'instructions'.

I'd like to get the shank size (in my exemple below : 6 X 1.6mm) 

Another problem I cant solve :  How can I  get a size after a lattice modifier.

![123](https://user-images.githubusercontent.com/11308387/58784392-95466600-85e3-11e9-96cc-b70d126b45ab.gif)

Thx for your quick reply. Then I'll wait for 2.3.3 release.

**Comment by mrachinskiy** [comment]
There are no instructions on how to use new features in v2.3.2.

> How can I get a size after a lattice modifier.

From what I can tell from your GIF, you are not using JewelCraft measurements, instead you used Measureit add-on, which has no relation to JewelCraft.

**Comment by bendicott67** [comment]
In fact,  dont know how can I gave to my founder the measurement of a shank
profil.

And as measure-it can't do it.... shouldn't it be interressant to get the
mesureament of a vertex group  instead of a mesh ?

**Comment by mrachinskiy** [comment]
> In fact,  dont know how can I gave to my founder the measurement of a shank profil.

Use object dimensions property.
