### ISSUE TITLE
Не подключается аддон

### ISSUE THREAD

**Issue by Helicoper** [mrachinskiy/jewelcraft#20]
Выдает ошибку при подключении. Как можно решить проблему?

![Screen Shot 2019-07-25 at 18 10 55](https://user-images.githubusercontent.com/53305225/61878470-80fb5700-af0a-11e9-8eee-7325e28398d4.png)
![Screen Shot 2019-07-25 at 18 11 50](https://user-images.githubusercontent.com/53305225/61878472-8193ed80-af0a-11e9-9e12-219fd7867830.png)

**Comment by mrachinskiy** [comment]
Версия аддона?

**Comment by mrachinskiy** [comment]
Текущая ошибка сообщает только о неудаче повторного запуска аддона, перезапустите Blender и попробуйте вызвать ошибку ещё раз, если она проявится, то сделайте её скриншот и отправьте мне.

**Comment by Helicoper** [comment]
Благодарю, Михаил. Все заработало на RC3 и JewelCraft 2.3.4.

По самомоу аддону. Михаил, очень нехватает функции "снять/установить галочки на всех вариантах сплавов" в свитке Weighting. 

Благодарю вас за прекрасный инструмент!
