### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by FadingFog** [mrachinskiy/jewelcraft#21]
![image](https://user-images.githubusercontent.com/10418075/63368582-dcdcc280-c386-11e9-86e0-8a98fa418f21.png)
Blender 2.80 Пробовал устанавливать как релиз, так и более новую версию аддона

**Comment by mrachinskiy** [comment]
Эта ошибка возникает когда пытаются установить репозиторий вместо релиза, поэтому просто следуйте [инструкции установки](https://github.com/mrachinskiy/jewelcraft#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0).
