### ISSUE TITLE
Error on Blender 2.8 Windows 10 when try to enable plugin.

### ISSUE THREAD

**Issue by elMaullido** [mrachinskiy/jewelcraft#22]
![Sin título-2](https://user-images.githubusercontent.com/57114103/67714963-40a7eb00-f9c9-11e9-9150-68d7386d7080.jpg)

**Comment by elMaullido** [comment]
Extended image
![Sin título-2](https://user-images.githubusercontent.com/57114103/67715211-a8f6cc80-f9c9-11e9-89f4-c887621b12af.jpg)

**Comment by mrachinskiy** [comment]
Please follow [How To Install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.
