### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by dpmimmo** [mrachinskiy/jewelcraft#24]
In Ubuntu 18.04 and Blender 2.81, JewelCraft 2.4.0 won't install:

bpy.data.window_managers["WinMan"].addon_search = ""
Failed to get add-ons path
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL', 'COMMUNITY'}
Failed to get add-ons path

**Comment by mrachinskiy** [comment]
Is this error message? I have never seen that one before. Could you please attach screenshot with the error message?

**Comment by lupeloca666** [comment]
Failed to install for me too I took a screen shot: 
![Screen Shot 2020-01-07 at 2 12 08 PM](https://user-images.githubusercontent.com/22628186/71933855-f1fc9700-3157-11ea-8fff-77f0094bd8c1.png)

**Comment by mrachinskiy** [comment]
> Failed to install for me too I took a screen shot:
> ![Screen Shot 2020-01-07 at 2 12 08 PM](https://user-images.githubusercontent.com/22628186/71933855-f1fc9700-3157-11ea-8fff-77f0094bd8c1.png)

You are trying to install add-on repository instead of release.
Please follow [install guide.](https://github.com/mrachinskiy/jewelcraft#how-to-install)

**Comment by dpmimmo** [comment]
JewelCraft 2.4.0 is for Blender 2.80. It won't install on Blender 2.81, the latest stable release.

**Comment by lupeloca666** [comment]
I tried it again last night with right file and it still doesn't install. it does on my friends blender but not mine, I screen shared with him to see what was wrong. It just doesn't show up in the list of add ons after installing, no error.

**Comment by mrachinskiy** [comment]
JewelCraft v2.4.1 is only for Blender 2.80, if you want to use Blender 2.79 you have to download JewelCraft v2.2.1 as it is specified in install guide.

**Comment by lupeloca666** [comment]
i know how to read and i picked the right one.

**Comment by mrachinskiy** [comment]
So there is no error message when you try to install v2.2.1? It's just not showing up in the add-ons list after you press install?

**Comment by lupeloca666** [comment]
no none it just doesn't show up in the list of add ons.

**Comment by mrachinskiy** [comment]
It might be that you did not remove your first add-on installation (that gave error) from Blender.
You still can do it manually.

1. First remove `jewelcraft` folder with all its contents from Blender's `addons` directory:
    * `/Users/your_user_name/Library/Application Support/Blender/2.79/scripts/addons`
3. Then unpack JewelCraft v2.2.1 archive to Blender's `addons` directory.

That should fix the issue.

**Comment by lupeloca666** [comment]
i will try it when i get home from work, i will post here and let you know, Thank you :)
