### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by dpmimmo** [mrachinskiy/jewelcraft#25]
Italian translation,
dpmimmo

[it.zip](https://github.com/mrachinskiy/jewelcraft/files/4088217/it.zip)

**Comment by mrachinskiy** [comment]
Hi, thank you so much for your contribution!

Is there a reason you did not translate following entries?
```
* [JewelCraft] Base
* Culet
* Enable widgets drawing
* Compose gem table and...
* Make collection instances...
* Asscher
* Radiant
* Flanders
```

**Comment by dpmimmo** [comment]
What are Culet and Asscher?

**Comment by mrachinskiy** [comment]
Culet is the tiny point at the base of the gemstone pavilion.
Asscher is a gemstone cut similar to emerald cut, but it has square shape.

**Comment by dpmimmo** [comment]
Translation rev. 1.0 :-)
[it.zip](https://github.com/mrachinskiy/jewelcraft/files/4089977/it.zip)

**Comment by mrachinskiy** [comment]
OK it's good.

Do you have any social net pages you want me to reference in announcement?
Maybe your name?

**Comment by dpmimmo** [comment]
I have a question: once I insert prongs, for example 3 items, and than I need to insert another one, There is the way to edit prongs?
https://www.facebook.com/depalo.gioielli
My name is De Palo Domenico

**Comment by mrachinskiy** [comment]
You could tweak it manually in edit mode, but that would be more complicated than creating a new prong object.
