### ISSUE TITLE
report error  two objects must be selected  jewelcraft 2.4.3 blender 2.81

### ISSUE THREAD

**Issue by sculp3d** [mrachinskiy/jewelcraft#26]
Hi 
An issue message is displayed when i clic anywhere on the work space, the message is displayed only when  jewelcraft is activated.

Thanks for your help

![jewelcraft-2_4_3- blender  2 81 issue](https://user-images.githubusercontent.com/582728/74008257-a3bdfc00-4980-11ea-8d98-2c95fae96595.jpg)
![jewelcraft-2_4_3- blender  2 81 issue2](https://user-images.githubusercontent.com/582728/74008261-a4ef2900-4980-11ea-97b2-34ba6a150d82.jpg)

**Comment by mrachinskiy** [comment]
Hi, I cannot reproduce the issue, could you please write step by step guide on how to reproduce it?

**Comment by mrachinskiy** [comment]
Closing for the lack of response from issue author.
