### ISSUE TITLE
The new 2.70 is not running on Mac. It installs on 2.82 but does not run anything. Where can I get 2.50 I hear that one works?

### ISSUE THREAD

**Issue by Cryptoguy911** [mrachinskiy/jewelcraft#27]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by mrachinskiy** [comment]
Please follow [how to install guide](https://github.com/mrachinskiy/jewelcraft#how-to-install).
