### ISSUE TITLE
Blender 2.83 LTS USE ADD GEM WILL FLASHBACK

### ISSUE THREAD

**Issue by kinomodo** [mrachinskiy/jewelcraft#28]
When adding gems in Blender 2.83 lts, ​​gems and icons cannot be displayed. If you click on the empty icon, Blender will flash back.

При добавлении драгоценных камней в Blender 2.83 LTS, драгоценные камни и значки не могут отображаться. Если вы нажмете на пустой значок, Blender вернется обратно.

**Comment by mrachinskiy** [comment]
Thanks for the report, the issue is fixed in JewelCraft 2.7.2, please update the add-on.
