### ISSUE TITLE
Can't enable a plug-in

### ISSUE THREAD

**Issue by martinpito** [mrachinskiy/jewelcraft#29]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system: win10 64bit
Blender version: 2.83
Add-on version:2.7.2
I've just downloaded a plug-in 2.72 and I install it successfully there was no issues but when I try to enable it I get this error and I don't know what to do with it can you help

**Screenshots**
http://somup.com/cY1f2sQfR5

**Comment by mrachinskiy** [comment]
You probably trying to install add-on repository instead of release, plese follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.

**Comment by martinpito** [comment]
Thank you I got it resolved

By the way, do you have some English video tutorial on how to use this
plugin?

Or even something more comprehensive and detailed? I'm willing to pay for it

**Comment by mrachinskiy** [comment]
There is a playlist of demonstration videos on my [youtube channel](https://www.youtube.com/playlist?list=PLCoK1Ao0T01KhfestF7xCic1jf5YjXiVh).

**Comment by martinpito** [comment]
Awesome thank you so much. I would like to get better at jewellery design
in Blender.

Are there any tutorials out there that you would recommend?

Thank you for your time
