### ISSUE TITLE
Error: Already Registered as subclass 'MeasurementCollection'

### ISSUE THREAD

**Issue by Dabblecat** [mrachinskiy/jewelcraft#30]
Operating system: Windows 10 64-bit
Blender version: 2.83
Add-on version: 2.7.2

![Screenshot (5)](https://user-images.githubusercontent.com/66840476/84524511-1846d580-aca8-11ea-86ce-9dc10dac0606.png)

**Comment by mrachinskiy** [comment]
You probably trying to install add-on repository instead of release, please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.

**Comment by Dabblecat** [comment]
thank you :)
