### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by hgq123** [mrachinskiy/jewelcraft#31]
![TIM图片20200618205510](https://user-images.githubusercontent.com/17998446/85022546-097b8980-b1a6-11ea-935b-d34a1528e737.png)
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by hgq123** [comment]
安装不起

**Comment by mrachinskiy** [comment]
You are trying to install add-on repository instead of release, please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.
