### ISSUE TITLE
Error occurence

### ISSUE THREAD

**Issue by dexe9** [mrachinskiy/jewelcraft#33]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system: win 10 x64
Blender version: 2.83
Add-on version: 2.7.3

**Describe the bug**
on the activation it says:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\jewelcraft\__init__.py", line 108, in <module>
    ui.VIEW3D_PT_asset_libs,
AttributeError: module 'jewelcraft.ui' has no attribute 'VIEW3D_PT_asset_libs'

**Screenshots**

**Comment by mrachinskiy** [comment]
Please provide full console output.
You can access the console from `Window` > `Toggle System Console`.

**Comment by dexe9** [comment]
Sorry, I don' understand what you mean by that, could you explain what series of command I've to input?
after I've opened the console what I must write here

**Comment by mrachinskiy** [comment]
You should copy the contents of the console window and paste them here.

**Comment by dexe9** [comment]
ok thank you, it's all right now, thanks for the time
