### ISSUE TITLE
jewqelcraft

### ISSUE THREAD

**Issue by 3insomniaD** [mrachinskiy/jewelcraft#34]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by 3insomniaD** [comment]
im making a hash of this

**Comment by 3insomniaD** [comment]
just wanted to adon jewelcraft to my blender

**Comment by 3insomniaD** [comment]
> **IMPORTANT**
> If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.
> 
> **Please complete the following information**
> Operating system:
> Blender version:
> Add-on version:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by mrachinskiy** [comment]
Invalid report.
