### ISSUE TITLE
weighting issue

### ISSUE THREAD

**Issue by AJWalker84** [mrachinskiy/jewelcraft#35]
I am using MacOS 11.0.1
I am on Blender V2.90.1
I am using Jewelcraft V2.8.1
I actually love Jewelcraft, let me start out by saying this. it allowed me to use blender instead of one of the insanely expensive jewellery creation suites out there. I have found 2 issues. the first is when calculating weight. I was calculating a complex multi piece ring design and when I selected all objects in the ring and had it calculate the total weight, it came back as significantly less than when I selected only the ring blank.  I tried a few different times, saved and restarted, tried with just 2 & 3 objects selected. in the end I had it calculate the weight for each asset separately and added them together, but it would be nice if I could be sure of it's reliance in calculating the weight of complex objects.  

**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by mrachinskiy** [comment]
Hi, could you please provide example scene?

**Comment by mrachinskiy** [comment]
Closing for the lack of response from issue author.
