### ISSUE TITLE
Иконки не отображаются

### ISSUE THREAD

**Issue by Sartemon** [mrachinskiy/jewelcraft#38]
Operating system: Windows 10 x64
Blender version: 2.92
Add-on version: 2.10.1

Иконки аддона не отображаются во вьюпорте. На скриншоте видно.
В целом, аддон работает прекрасно, но иконки, все же, добавили бы изящности.

![Багрепорт](https://user-images.githubusercontent.com/81856423/113475661-b39b7800-947f-11eb-9577-b6c61aa7ba8a.jpg)

**Comment by Sartemon** [comment]
В предыдущих версиях Blender и Jewelcraft такой проблемы не было, на этом же компьютере.

**Comment by mrachinskiy** [comment]
Какой Render Engine выбран в настройках ренедра?

**Comment by Sartemon** [comment]
![image](https://user-images.githubusercontent.com/81856423/113506527-0d6a7380-954e-11eb-9a64-5cd763734658.png)
Workbench
При других Render Engines тот же результат
![image](https://user-images.githubusercontent.com/81856423/113506547-2d019c00-954e-11eb-8d6c-237cfca81433.png)
![image](https://user-images.githubusercontent.com/81856423/113506550-34c14080-954e-11eb-9dc9-d0c2e50681c8.png)

**Comment by Sartemon** [comment]
Но я заметил, что и в HardOps похпжая проблема: не все иконки отображаются, что в боковом меню, что в верхнем.
Наверное, это какой-то баг в самой программе.
![image](https://user-images.githubusercontent.com/81856423/113506656-ca5cd000-954e-11eb-8c44-cc5112a2c29a.png)

**Comment by mrachinskiy** [comment]
Это известная проблема, она указана в разделе [Known Issues](https://github.com/mrachinskiy/jewelcraft#known-issues).

В Blender 2.92 и других ранних версиях при выборе Workbench как Render Engine превью изображений не загружаются в интерфейс.

Для решения проблемы:
- Выставите другой Render Engine, сохраните как дефолтную настройку и перезапустите Blender (смена рендера без перезапуска Blender не сработает).
- Либо используйте Blender 2.93, там эта ошибка исправлена.

**Comment by Sartemon** [comment]
Спасибо! Помогла замена рендера.
Удачи и здоровья!
![image](https://user-images.githubusercontent.com/81856423/113551339-254d0080-95fd-11eb-9dc3-46f0fa07e26f.png)
