### ISSUE TITLE
Update Suggestion

### ISSUE THREAD

**Issue by mzindiaumia** [mrachinskiy/jewelcraft#39]
Just wondering if jewelcraft could be updated so that the jewels would automatically be unwrapped.

**Comment by mrachinskiy** [comment]
What is the use case for UVs in gems?

**Comment by mzindiaumia** [comment]
to create the textures in photoshop or render in blender

**Comment by mrachinskiy** [comment]
Reflection or refraction cannot be convincingly simulated with UV textures, for detail texture (like scratches and inclusions) other texture mapping methods (like box projection) are good enough.

If you have a particular workflow, then you can create UVs yourself and use in add-on asset manager to store gem models with UVs.

At this moment I do not see a compelling reason to include UV coordinates with Add Gem tool.
