### ISSUE TITLE
Bug with adding gemstone on blender 2.93.0

### ISSUE THREAD

**Issue by joe-conigliaro** [mrachinskiy/jewelcraft#41]
Operating system: macOS 11.3.1
Blender version: 2.93.0 Beta - (April 19, 12:08:45- c75b2019e101 - macOS Arm 64 bit)
Add-on version: 2.10.1

When trying to add a gemstone the dropdown to select gemstone type is not populated, and the stone shape image is missing.

I'm not sure if this is a bug with the 2.93.0 beta or if is something specifically with the Mac arm64 build.

Btw Great Plugin, thanks! 🙃
<img width="359" alt="Screen Shot 2021-05-08 at 9 10 59 am" src="https://user-images.githubusercontent.com/2801678/117520969-957ce680-afee-11eb-8a7c-132fb29613ae.png">
<img width="737" alt="Screen Shot 2021-05-08 at 9 11 17 am" src="https://user-images.githubusercontent.com/2801678/117520972-99a90400-afee-11eb-9ed7-466d005c57d5.png">

**Comment by mrachinskiy** [comment]
It is a bug in Blender April dev builds, update to recent dev build.

**Comment by joe-conigliaro** [comment]
Thanks @mrachinskiy
