### ISSUE TITLE
Unable to click check box

### ISSUE THREAD

**Issue by Siyouardi** [mrachinskiy/jewelcraft#42]
After installing the addon the check box is unclickable to activate the addon. 
![Screen Shot 2021-07-03 at 8 47 25 PM](https://user-images.githubusercontent.com/61252816/124372567-f1a36600-dc3f-11eb-8504-8c451ef68ec8.png)

**Comment by mrachinskiy** [comment]
You are trying to install add-on repository instead of release, please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.
