### ISSUE TITLE
Apple showing error for Jewelcraft add on

### ISSUE THREAD

**Issue by Ngloreusbasterd** [mrachinskiy/jewelcraft#43]
I have downloaded the 2.9 version of Blender 3 times and jewel craft add on multiple times from GitHub link. Shows an error when enabling the add-on.   Has anyone found a solution for this?
[Blender error.pdf](https://github.com/mrachinskiy/jewelcraft/files/6794581/Blender.error.pdf)

**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**

**Comment by mrachinskiy** [comment]
Add-on folder name cannot contain dash `-` symbol.
Also please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.

**Comment by Ngloreusbasterd** [comment]
I tried downloading this file and taking out the dashes in the file name.  Didn't work.  I did finally find something that may help out Apple users that use Safari and unzipping files.

Right click on the Jewelcraft link.  choose download directly to desktop.  Go into Blender and follow the install directions for the add on and choose the directly to desktop file.  I have been working on troubleshooting this for 4 nights now and this finally worked.  Thanks for such an awesome program.  I will definitely be contributing funds to help keep this as awesome as you can.
