### ISSUE TITLE
"Scene scale not optimal" warning

### ISSUE THREAD

**Issue by ebyrobin** [mrachinskiy/jewelcraft#45]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
windows 10
Blender version: 3.0
Add-on version:2.12

**Describe the bug**
"Scene scale not optimal" warning is on the top when I open jewelcraft. I am not able to change units. When i press the change unit button, it closes.

**Screenshots**

**Comment by mrachinskiy** [comment]
Could you run Blender from command line?

1. Open windows Start menu and type `cmd`.
2. It will find Command Prompt app, open it.
3. Drop `blender.exe` into Command Prompt window and press `Enter`.
4. It will launch Blender, now cause Blender to crash with JewelCraft add-on and send back screenshot of the output you got in Command Prompt.

**Comment by mrachinskiy** [comment]
You have to attach screenshot to a GitHub issue, you cannot do that through the email.
Click `view it on GitHub` link in the bottom of this email, it will get you to GitHub issue.

**Comment by ebyrobin** [comment]
Here it is.
![Screenshot (2)](https://user-images.githubusercontent.com/84685507/153101261-c14066b4-a5a7-4b40-801d-8b00c6339071.png)

**Comment by mrachinskiy** [comment]
It seems you did not drop Blender executable file to command line window, but instead just typed `blender.exe`.
That wouldn't work, you have to drop an actual executable file for it to work.

**Comment by mrachinskiy** [comment]
Closing for the lack of response from issue author.
