### ISSUE TITLE
Blender closes itself

### ISSUE THREAD

**Issue by lului22129** [mrachinskiy/jewelcraft#47]
I downloaded the jewelcraft addon and I can install it correctly, the problem comes after adding a gem and want to add prongs or make any other setting, I automatically closes blender and so it is impossible to make jewelry.
Please help me
I use blender 3.1.
[Blender 2022-03-28 16-08-37.zip](https://github.com/mrachinskiy/jewelcraft/files/8363532/Blender.2022-03-28.16-08-37.zip)
.

**Comment by mrachinskiy** [comment]
Could you run Blender from command line?

1. Open windows Start menu and type `cmd`.
2. It will find Command Prompt app, open it.
3. Drop `blender.exe` into Command Prompt window and press `Enter`.
4. It will launch Blender, now cause Blender to crash with JewelCraft add-on and send back screenshot of the output you got in Command Prompt.

**Comment by lului22129** [comment]
It tells me that it is not recognized as an internal or external command.
I have it downloaded from steam.

**Comment by lului22129** [comment]
It tells me that it is not recognized as an internal or external command.
I have it downloaded from steam.

**Comment by mrachinskiy** [comment]
You have to drop blender.exe file into command line, not type it in.

**Comment by lului22129** [comment]
![Captura de pantalla 2022-03-28 175957](https://user-images.githubusercontent.com/102533289/160439441-7b6ad928-13a8-429a-b043-2e481f33493b.png)

it's weird, because I used the jewelry addon.

**Comment by lului22129** [comment]
![Captura de pantalla 2022-03-28 175957](https://user-images.githubusercontent.com/102533289/160439510-8d2953dc-3868-42b1-bee1-b09a3586b78b.png)
it's weird, because I used the jewelry addon.

**Comment by lului22129** [comment]
it's weird, because I used the jewelry addon
![Captura de pantalla 2022-03-28 175957](https://user-images.githubusercontent.com/102533289/160439594-0c6da441-1071-4f84-b171-6b05bb2767ce.png)
.

**Comment by mrachinskiy** [comment]
I'm pretty sure JewelCraft is not the reason for Blender crash. To confirm it open Blender, then use File > Defaults > Load Factory Settings, then enable JewelCraft in preferences and try to work with it.

**Comment by lului22129** [comment]
It's working!! Thank you
