### ISSUE TITLE
Blender 3.1 doesn't work

### ISSUE THREAD

**Issue by AdamJeweler** [mrachinskiy/jewelcraft#48]
[**IMPORTANT**](url)
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:3.1
Add-on version:

**Describe the bug**
Can't Add Jewelcraft in the préférence menu
**Screenshots**

**Comment by mrachinskiy** [comment]
Please provide information such as add-on version and error screenshot.

**Comment by mrachinskiy** [comment]
Closing for the lack of response from issue author.
