### ISSUE TITLE
Traditional Chinese （zh-TW）translation file

### ISSUE THREAD

**Issue by bisechen** [mrachinskiy/jewelcraft#49]
This is the translation file in traditional language, only some proper nouns have not been translated, the rest have been translated, I have no social networking site, only email bise.chen@gmail.com

I couldn't upload the .po file, so I added the txt extension.

[zh_TW.po.txt](https://github.com/mrachinskiy/jewelcraft/files/8953935/zh_TW.po.txt)

**Comment by mrachinskiy** [comment]
Thank you so much! Your translation will be available in the next release.

**Comment by mrachinskiy** [comment]
I think it is better to feature your GitHub profile, it has your email anyway.

**Comment by mrachinskiy** [comment]
Is there a reason you did not translate these five gem cut names? I noticed those are also not translated in Simplified Chinese version.

- Asscher
- Radiant
- Flanders
- Trillion
- Trilliant

**Comment by bisechen** [comment]
> Is there a reason you did not translate these five gem cut names? I noticed those are also not translated in Simplified Chinese version.
> 
> * Asscher
> * Radiant
> * Flanders
> * Trillion
> * Trilliant

The website can use https://github.com/bisechen

The proper nouns of some gems are usually only transliterated without the translation of Chinese nouns, so we will not do translations for the time being.
