### ISSUE TITLE
Report Error : Selected Objects do not have Follow Path constraint

### ISSUE THREAD

**Issue by k-a-s-o-u** [mrachinskiy/jewelcraft#51]
Operating system:
Blender version:3.2.1
Add-on version:2-12-0,2-13-1

**Describe the bug**
Report Error : Selected Objects do not have Follow Path constraint  window error message pop up when click LMB. even though at new general file.
It didn't happened only on Blender 3.1.2 for some reason.
I tried uninstalled and installed multiple version of Blender but didn't fix.
When JewelCraft Add-on uncheck then error pop-up doesn't happen.
Thank you.
 

**Screenshots**
![スクリーンショット 2022-08-02 03 16 10](https://user-images.githubusercontent.com/29495485/182215940-8762e810-bb22-4169-b9d4-5d095a391de7.png)

**Comment by mrachinskiy** [comment]
Hi, please use File > Defaults > Load Factory Settings, then enable JewelCraft and see if issue still appears.

**Comment by mrachinskiy** [comment]
Close for the lack of response from issue author.
