### ISSUE TITLE
Stones sizes

### ISSUE THREAD

**Issue by Emilien-Etadam** [mrachinskiy/jewelcraft#54]
Hi, thank you so much for this great addon !

Is it possible to show stones sizes like Spacing Overlay do ? 
Is it possible also to color stones depending the sizes ?

I know the gem map do it but I would like to see it during the stone mapping.

Many Thanks

**Comment by mrachinskiy** [comment]
Hi, right now it is not possible, I already thought to add other overlays like gem size, but at the moment I'm not sure how to implement it so it would look decent and wont drastically slowdown viewport.

**Comment by Emilien-Etadam** [comment]
Just for selected stone and the stones around ?
![3qca2Dx62L](https://github.com/mrachinskiy/jewelcraft/assets/56485277/2904890f-6a3c-4eda-94c0-d5d8f7d284d7)
How about the colors ? It possible ?

**Comment by mrachinskiy** [comment]
Everything is possible, I just need to figure out how to implement it.

**Comment by mrachinskiy** [comment]
Unfortunately, ChatGPT is not available to me, due to sanctions.
