### ISSUE TITLE
jewelcraft zh_CN.po

### ISSUE THREAD

**Issue by 1848469517** [mrachinskiy/jewelcraft#56]

**Comment by 1848469517** [comment]
[zh_CN.zip](https://github.com/mrachinskiy/jewelcraft/files/13693666/zh_CN.zip)

**Comment by mrachinskiy** [comment]
Thank you so much for the contribution! Can I have your name and social links to credit you in release notes, or do you prefer to remain anonymous?

**Comment by mrachinskiy** [comment]
Fixed by 7ad2b5ac
