### ISSUE TITLE
Chinese language cannot be displayed

### ISSUE THREAD

**Issue by bisechen** [mrachinskiy/jewelcraft#57]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version: 4.0 
Add-on version:2.15.0

**Describe the bug**
Chinese language cannot be displayed.

After blender 4.0, the Chinese language system has changed. zh_tw has become zh_HANT, and zh_CN has become zh_HANS. This may be why I cannot display the Chinese language system when using jewelcraft in blender 4.0. Please check and correct it.

**Screenshots**

**Comment by mrachinskiy** [comment]
You are correct, I did not notice a change to locale names. Will be fixed in the upcoming release.
