### ISSUE TITLE
Zh_TW (zh_HANT) language translation file

### ISSUE THREAD

**Issue by bisechen** [mrachinskiy/jewelcraft#58]
Attach .po translation file, additionally provide your name and social network page to be featured in announcement.
[zh_TW.zip](https://github.com/mrachinskiy/jewelcraft/files/13712472/zh_TW.zip)

**Comment by mrachinskiy** [comment]
Thank you for the update localization!

**Comment by mrachinskiy** [comment]
Commited 7ad2b5aca8

**Comment by bisechen** [comment]
> 已提交 [7ad2b5a](https://github.com/mrachinskiy/jewelcraft/commit/7ad2b5aca8219aff2e0c64faaec3efe022a1607f)

thank you for your update..^^
