### ISSUE TITLE
traceback error when installing 

### ISSUE THREAD

**Issue by spxcyz** [mrachinskiy/jewelcraft#59]
![Screenshot 2024-01-13 204109](https://github.com/mrachinskiy/jewelcraft/assets/115798776/5b04677e-f53f-460f-9853-8e687ffdb8fb)
followed instructions and i got this error

**Comment by mrachinskiy** [comment]
You are trying to install add-on repository instead of release, please follow [how to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide for proper installation process.
