### ISSUE TITLE
Error upon install addon

### ISSUE THREAD

**Issue by infinitekiwi** [mrachinskiy/jewelcraft#6]
![](https://i.gyazo.com/790d708f2857d7a29d80ff5105244601.png)

**Comment by chris-aeviator** [comment]
I'm experiencing the same error with Blender 2.78 - @infinitekiwi how did you solve your issue since you did not leave any hints on follow up users =)

**Comment by mrachinskiy** [comment]
Blender 2.78 is not supported. Please read [How to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.
