### ISSUE TITLE
Error intall blender 3.5 or superior

### ISSUE THREAD

**Issue by MFN69** [mrachinskiy/jewelcraft#60]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system:
Blender version:
Add-on version:

**Describe the bug**

**Screenshots**
![image](https://github.com/mrachinskiy/jewelcraft/assets/123533474/06267bb5-3a38-4173-8f60-055954dc64cc)
![Screenshot_1](https://github.com/mrachinskiy/jewelcraft/assets/123533474/314fa2d5-e556-4d9d-aa2d-32b3ed9a812d)
error and install

**Comment by MFN69** [comment]
windows 10 - Blender 3.5

**Comment by mrachinskiy** [comment]
You are trying to install add-on repository instead of release, make sure you download add-on release using link provided in step one of [installation guide](https://github.com/mrachinskiy/jewelcraft#how-to-install).

**Comment by MFN69** [comment]
hello thank you very much it works. you're very kind. God bless you.
