### ISSUE TITLE
Ring sizing calculation is incorrect

### ISSUE THREAD

**Issue by TheSlowhandZA** [mrachinskiy/jewelcraft#61]
Blender all verisons 

your ring sizing calculation in the software are based on the outside circumference and diameter of the ring which is incorrect and means the sizes are wrong by anything up to 4 sizes. in jewelery we use the inside circumference and diameter of the ring to get the ring size , as the wall thickness could be anything. please fix this

**Comment by mrachinskiy** [comment]
Could you please provide blend file with the issue?

**Comment by TheSlowhandZA** [comment]
its telling me that the file is too big to send to you via github, please
provide me with an actual email address

original msg

"sure,

you will see your models along side aring of mine, please keep private .
the inner circumference of the ring is 17. something, your report is
showing me the outside circumference which is know to be 19 , whatever.

Thanks in advance, its an amazing piece of software. let me know how we
resolve this issue
"

**Comment by mrachinskiy** [comment]
Here is my email: mikhail.rachinskiy@gmail.com

But you don't need to send me your productions file, just recreate the issue in test file with simple objects.

**Comment by mrachinskiy** [comment]
You used shank object `batshank` in ring size measurement, instead pick size curve object `Size.005` and you will get correct measurements.

**Comment by TheSlowhandZA** [comment]
the batshank object is the object that i wanted to get the size for. for
batshank, its ring size is 17.5 , but instead its showing me the outside
measurements. this happened last night in a  different file too, i simply
shared this one with you so that you could see what the issue is.  if i
select object size.005 it will give me the ring size of your ring model and
not mine..

[image: image.png]

M

**Comment by mrachinskiy** [comment]
Ring size measurement just gets object dimensions, you have to pick object that defines ring size (like size curve) or create object that will be equal to ring size and pick that.

**Comment by TheSlowhandZA** [comment]
ah, ok, that i do in another programme where i use a cylinder shape to
figure out what the ring size is. appreciate the help.

bought the Udemy course this morning, busy going through it and learning
what i need to, thank you so much for great software and thank the person
who put the course together, finally i can stop fumbling through
youtube tutorials in the wrong order around blender.

much appreciated

M
