### ISSUE TITLE
大佬,可否在"曲线-创建曲线-格式-(添加香港的尺寸)"

### ISSUE THREAD

**Issue by BFMEILI** [mrachinskiy/jewelcraft#62]
大佬,可否在"曲线-创建曲线-格式-(添加香港的尺寸)",
![72e470e5-7eb1-4e9c-9c06-21a0d2da50f2](https://github.com/mrachinskiy/jewelcraft/assets/171265649/314db73e-c75c-4c8a-bfa1-400c05923764)
谢谢

**Comment by mrachinskiy** [comment]
Hi, Hong Kong ring size was available at some point before, but later I removed it since I was not able to find a reliable size chart, every single size chart was different from another.
If you can provide me with reliable size chart, then I'll add Hong Kong ring size back in.

**Comment by BFMEILI** [comment]
![047e4b98-b307-46af-b449-be8e4af553e9](https://github.com/mrachinskiy/jewelcraft/assets/171265649/e0aadb8e-8eee-48b8-843c-0a57da49110c)
![801dc21f-c6b6-4656-9ea1-aceda1f0216f](https://github.com/mrachinskiy/jewelcraft/assets/171265649/379b58d9-b778-4ad7-913e-194c867b5318)
![796683e5-dcea-4232-9850-0df581846eb8](https://github.com/mrachinskiy/jewelcraft/assets/171265649/8629396a-b4a6-4bdf-95c6-caccf2c11a33)
![c2ef9e4f-ace4-487c-b297-dc49f0d4cc85](https://github.com/mrachinskiy/jewelcraft/assets/171265649/d804d427-041c-4c94-b1e8-fd4195d9153e)
![网页捕获_31-5-2024_141158_wills hk](https://github.com/mrachinskiy/jewelcraft/assets/171265649/3f424831-657a-444b-99ff-600b01da56b0)
这是我在网上找到的一些,可以参考

**Comment by mrachinskiy** [comment]
These are not reliable; they get all known sizes incorrectly including US, (especially) British, Swiss and I imagine Hong Kong sizes are also incorrect.

British G size is incorrect by 0.4mm! (Bloody hell!)

![size chart](https://github.com/mrachinskiy/jewelcraft/assets/10104625/810a921c-0f2c-4248-b335-616e333a19f3)

I took US, British and Swiss from official sources, I failed to find Japanese official source, but discrepancy was not so big between unofficial sources.

HK size charts are all over the place, I cannot include it.

Do you have access to JewelCAD or know a person that has access to it? It is the most popular tool in Hong Kong, and it would be the most reliable source for ring sizes. If you give me size chart from JewelCAD, I will definitely include it.

**Comment by mrachinskiy** [comment]
I found out that JewelCAD doesn't even have HK ring size. I guess they also couldn't find a reliable source.

So, I dug around and again found nothing on HK size.
I took ring size guides from three different jewelry providers in HK for comparison, and they all mismatch. Not a single one of them matches any guide provided here or on the internet. Where do they take these numbers from?

Before I close this thread, could you please provide additional information?
Why do you need HK ring size? Is anyone asking you to provide that?

**Comment by mrachinskiy** [comment]
I decided that it would not be fair to exclude HK ring size but include JP since they both don't have spec.
I referenced size chart from one of the HK jewelry providers.

If anyone has spec or a good reason to believe that they have correct size chart for either HK or JP ring size, then please contact me.
