### ISSUE TITLE
Please Add Design Report in JSON Format Option in Preferences

### ISSUE THREAD

**Issue by sureshM470** [mrachinskiy/jewelcraft#64]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system: Windows 11
Blender version: 4.2
Add-on version: 2.16.0

**Describe the bug**
Design Report support only HTML file, Please Add support for JSON reports.

**Screenshots**

**Comment by mrachinskiy** [comment]
Could you please tell me more about your workflow and why you need specifically JSON report?

**Comment by sureshM470** [comment]
I'm looking to generate json design reports , so I can use json to upload
to my designs database.

**Comment by mrachinskiy** [comment]
Yeah, I'll add the option in the next feature release.

**Comment by sureshM470** [comment]
Thanks

**Comment by mrachinskiy** [comment]
What structure would you want this to be? Right now, it's like this:

```json
{
    "gems": [
        [
            "Diamond",
            "Round",
            "5.0",
            0.457,
            1,
            0.457
        ],
        [
            "Topaz",
            "Round",
            "2.2",
            0.039,
            6,
            0.234
        ],
        [
            "Topaz",
            "Round",
            "1.8",
            0.022,
            4,
            0.088
        ]
    ]
}
```

**Comment by sureshM470** [comment]
can we have something like this: 
{
    "gems": [
        {
           "stone": "Diamond",
           "cut": "Round",
            "size":"5.0"
        },
        {
            "stone": "Topaz",
             "cut": "Round",
             "size":"2.2"
        }
    ]
}

**Comment by mrachinskiy** [comment]
Would that be good enough?

```json
{
    "metadata": {
        "Project": "Awesome Ring",
        "Date": "2024-08-04"
    },
    "gems": [
        {
            "stone": "Diamond",
            "cut": "Round",
            "size": "5.0",
            "ct": 0.457,
            "qty": 1,
            "ct_sum": 0.457
        },
        {
            "stone": "Topaz",
            "cut": "Round",
            "size": "2.2",
            "ct": 0.039,
            "qty": 6,
            "ct_sum": 0.234
        },
        {
            "stone": "Topaz",
            "cut": "Round",
            "size": "1.8",
            "ct": 0.022,
            "qty": 4,
            "ct_sum": 0.088
        }
    ],
    "materials": {
        "Yellow Gold 24K": "3.2 g"
    },
    "notes": {
        "Ring Size (Diameter)": "16.0 mm",
        "Shank Dimensions": "18.78 × 2.77 × 21.08 mm"
    }
}
```

**Comment by sureshM470** [comment]
Yes

**Comment by mrachinskiy** [comment]
JSON export feature will be available in next release.
