### ISSUE TITLE
Extensions link not working in Blender 4.2.2 

### ISSUE THREAD

**Issue by CerealExperiments45** [mrachinskiy/jewelcraft#65]
**IMPORTANT**
If error occurs on add-on installation or activation you probably trying to install add-on repository instead of release, check how to install guide (on the main page) for proper installation process.

**Please complete the following information**
Operating system: Windows 10
Blender version: 4.2.2
Add-on version: 2.17.0

**Describe the bug**
When I try to install from the Extensions tab with the link from the main page I get this error: 

install: HTTP error (HTTP Error 404: Not Found) reading 'https://mrachinskiy.github.io/api/v1/extensions.json'!

**Screenshots**
![Jewelcraft error - 26OCT20244](https://github.com/user-attachments/assets/1c507b18-b3e5-406c-8cdb-fc5b52971e30)

**Comment by mrachinskiy** [comment]
Thanks for the report, issue if fixed.

**Comment by CerealExperiments45** [comment]
Fixed. You're a legend!
