### ISSUE TITLE
Reproducable bug: Blender crashes after scattering generated gem along curve and then hitting "undo" 

### ISSUE THREAD

**Issue by GesaP** [mrachinskiy/jewelcraft#7]
Blender crashes after scattering generated gem along curve and then hitting "undo"

Happened to me twice in a row now, and earlier the week.
Curve was made by creating a mesh oval and alt+c to curve. 
No changes to gems were made after scattering.

(If this is the wrong place for reporting this, happy to move it)

**Comment by mrachinskiy** [comment]
What version of Blender are you using?

**Comment by GesaP** [comment]
Thanks for the quick reply,
2.79b.

**Comment by mrachinskiy** [comment]
Could you please run Blender from console in debug mode, like so:
`C:\Users\Username\blender-2.79b> .\blender.exe --debug`
And after it crashes send me console output.

Also send `system-info.txt` from `Help` > `Save System Info`.

**Comment by mrachinskiy** [comment]
I will reopen the issue if bug reappears and could be reproduced.
