### ISSUE TITLE
Error on initial Install

### ISSUE THREAD

**Issue by chris-aeviator** [mrachinskiy/jewelcraft#9]
When installing the addon as described (Blender 2.78, Ubuntu 16.04) the addon does not enable itself automaticall. When trying to enable the addon, Blender outputs the following

![](https://camo.githubusercontent.com/306fa2ba43de6b13aabd32220d7db6e7b9d3e1ba/68747470733a2f2f692e6779617a6f2e636f6d2f37393064373038663238353764376132396438306666353130353234343630312e706e67)

(image taken from #6 which was closed without any comment)

**Comment by mrachinskiy** [comment]
Blender 2.78 is not supported. Please read [How to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.

**Comment by Arkvys** [comment]
After refreshing Blender 2.8 with latest build., the add-on isn't working properly. Not showing the stone shapes. I downloaded it from your site, but now it wont start. Here is the screenshot.
http://prntscr.com/mxyujf
Thank you.

**Comment by mrachinskiy** [comment]
@Arkvys did you remove the previous add-on version before installing the new one?

**Comment by Arkvys** [comment]
Yes I did.

**Comment by mrachinskiy** [comment]
Have you tried reactivate the add-on after closing and opening Blender?
Which link on the github page you used to download the add-on?

**Comment by bendicott67** [comment]
I add the same problem. I deleted manually the script in Appdata Blender directory on Win10. 
Something like : C:\Users\[profile]\AppData\Roaming\Blender Foundation\...

**Comment by mrachinskiy** [comment]
@bendicott67 same questions:
Have you tried reactivate the add-on after closing and opening Blender?
Which link on the github page you used to download the add-on?
Also please provide screenshot of the error that you get.

**Comment by bendicott67** [comment]
It is Ok for me now.  After I deleted manually the jewelcraft & booltron folder script in  ...\AppData\Roaming\Blender Foundation... , I reinstalled the '***-master.zip' scripts from GitHub and  it was ok ;) 
Sry, I didn't save the error pb.

**Comment by Arkvys** [comment]
I've restarted Blender but I still couldn't activate the add on. Here is
the link i used to download the file:
https://github.com/mrachinskiy/jewelcraft

**Comment by mrachinskiy** [comment]
> @bendicott67
> It is Ok for me now... I reinstalled the '*-master.zip' scripts from GitHub and it was ok ;)

If you use Blender 2.80 then old add-on version from `*-master.zip` archives will work only until you use automatic updates. You have to download and install the new versions.

> @Arkvys
> Here is the link i used to download the file: https://github.com/mrachinskiy/jewelcraft

This is not the link to download the add-on, this is the link to a GitHub page, which link you used to download the add-on?

**Comment by Artist-alt** [comment]
thank you so much..... I'm using MAC

regarding the 2.6 version 

 there is errors message: 



.......Line 382 in enable mode.register()


.......Line 186, in register bpy.utils.register_class(cls)


ValueError.register_class(....): already registered 'MeasurementCollection'


...............


 found same error with last version..... that time i search for (register_class) i found it in other add-one 

{Pipe Add-one..... so i change it to (register_class0)} 



and it was fix......

i trying same way with this version..... still not working



..............

def register():
    for cls in classes:

        bpy.utils.register_class(cls)
..............



Please help.... thanks and all the best

**Comment by mrachinskiy** [comment]
@Artist-alt Please follow [how to install guide](https://github.com/mrachinskiy/jewelcraft#how-to-install).
